// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace TCDF.Sinj.Web {
	
	
	public partial class EditarLinks {
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl div_conteudo_arquivo;
		
		protected System.Web.UI.HtmlControls.HtmlInputHidden id_doc;
		
		protected System.Web.UI.HtmlControls.HtmlInputHidden id_file;
		
		protected System.Web.UI.HtmlControls.HtmlInputHidden nm_arquivo;
	}
}
