// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace TCDF.Sinj.Web {
	
	
	public partial class RecriarSenhaNotifiqueme {
		
		protected System.Web.UI.WebControls.Content Content1;
		
		protected System.Web.UI.WebControls.Content Content2;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl div_form_recriar_senha;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl div_info_recriar_senha;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl div_form_nova_senha;
	}
}
